# Generated by Django 3.0.2 on 2020-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropProj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DronePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DroneID', models.IntegerField(max_length=20)),
                ('PartID', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PartSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecID', models.IntegerField(max_length=20)),
                ('PartID', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ESC',
        ),
        migrations.DeleteModel(
            name='FC',
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.DeleteModel(
            name='Motors',
        ),
        migrations.DeleteModel(
            name='RX',
        ),
        migrations.DeleteModel(
            name='TX',
        ),
    ]
