# Generated by Django 3.0.2 on 2020-01-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PropProj', '0002_auto_20200104_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='Owner',
        ),
    ]
