# Generated by Django 3.0.2 on 2020-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropProj', '0004_auto_20200105_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='ImageUrl',
            field=models.CharField(default=1, help_text='image of part', max_length=350),
            preserve_default=False,
        ),
    ]
